#!/usr/bin/env perl
use strict;
use warnings;
use Data::Dumper;

sub usage {
  print <<USAGE;
Usage: git copy src dest
       git cp src dest
USAGE
  exit(1);
}

sub main {
    my ($src, $dest) = @_;

    unless ($src) {
        usage();
    }

    unless ($dest) {
        usage();
    }

    exec "cp $src $dest";
}

main(@ARGV);

__END__

=head1 NAME

git-copy - git subcommand for cp(1)

=head1 SYNOPSIS

  $ git copy src dest

=head1 DESCRIPTION

  $ git clone https://github.com/kyanny/git-copy
  $ export PATH=./git-copy:$PATH
  $ git copy

=head1 AUTHOR

Kensuke Nagae <kyanny at gmail dot com>

=head1 LICENSE

http://kyanny.mit-license.org/

=cut

